// Generated by cs2-sdk - https://cs2-sdk.com
// Resolved global addresses from the signature + offset passes.
//
// Two namespace trees are emitted:
//   cs2::offsets::<module>          — signature-resolved interface/global pointers
//   cs2_dumper::offsets::<module>_dll — a2x/cs2-dumper drop-in (dwXxx names)
#pragma once

#include <cstddef>
#include <cstdint>

namespace cs2::offsets {
    // Module: animationsystem.dll
    namespace animationsystem {
        constexpr uintptr_t AnimationSystemUtils_ptr = 0x812170;
    }
    // Module: client.dll
    namespace client {
        constexpr uintptr_t GlobalVariables_ptr = 0x205E6D0;
        constexpr uintptr_t GameRules_ptr = 0x233E258;
        constexpr uintptr_t GameEntitySystemPtr = 0x24E44E0;
        constexpr uintptr_t ParticleManager_ptr = 0x2042B38;
        constexpr uintptr_t CSGOInput_ptr = 0x2076830;
        constexpr uintptr_t ClientMode_ptr = 0x2350F40;
        constexpr uintptr_t ViewRender_ptr = 0x2343E58;
        constexpr uintptr_t VPhys2World_ptr = 0x2042990;
        constexpr uintptr_t GetBBox_ptr = 0x233E258;
        constexpr uintptr_t GetInstanceS = 0x22CC910;
        constexpr uintptr_t GlowManager_ptr = 0x233B050;
        constexpr uintptr_t Sensitivity_ptr = 0x233BB60;
        constexpr uintptr_t EntityList_ptr = 0x24E44E0;
        constexpr uintptr_t ViewMatrix_addr = 0x2343AB0;
        constexpr uintptr_t PlantedC4Alt_ptr = 0x234CF08;
        constexpr uintptr_t GameRulesAlt_addr = 0x1A00BB0;
        constexpr uintptr_t Prediction_ptr = 0x2069710;
        constexpr uintptr_t WeaponC4_ptr = 0x22BBE30;
        constexpr uintptr_t LocalPlayerController_ptr = 0x231D830;
        constexpr uintptr_t global_vars_v2 = 0x233E258;
        constexpr uintptr_t local_controller = 0x231D830;
        constexpr uintptr_t entity_list_ptr = 0x24E45E8;
        constexpr uintptr_t view_matrix_ptr = 0x2343AB0;
        constexpr uintptr_t planted_c4_ptr = 0x22BBE30;
        constexpr uintptr_t CSGOInput_resolved = 0x2076837;
        constexpr uintptr_t CInputPtrGlobal = 0x2076830;
        constexpr uintptr_t MainMenuPanelPointer = 0x23A04C8;
        constexpr uintptr_t HudPanelPointer = 0x23AD330;
        constexpr uintptr_t GlobalVarsPointer = 0x205E6D0;
        constexpr uintptr_t TransformTranslate3dVMT = 0x1B01858;
        constexpr uintptr_t TransformScale3dVMT = 0x1B0A110;
        constexpr uintptr_t WorldToProjectionMatrixPointer = 0x2343AB0;
        constexpr uintptr_t ViewToProjectionMatrixPointer = 0x2343A70;
        constexpr uintptr_t ManageGlowSceneObjectPointer = 0xADF400;
        constexpr uintptr_t SetSceneObjectAttributeFloat4 = 0x1740D0;
        constexpr uintptr_t PointerToClientMode = 0x2350F40;
        constexpr uintptr_t CvarPointer = 0x2555108;
        constexpr uintptr_t GetAbsOriginFunction = 0x20DDD0;
        constexpr uintptr_t EntitySystemPointer = 0x2327590;
        constexpr uintptr_t GameRulesPointer = 0x233E258;
        constexpr uintptr_t SetImageFunctionPointer = 0x167F4A0;
        constexpr uintptr_t ImagePanelConstructorPointer = 0x167C3A0;
        constexpr uintptr_t LabelPanelConstructorPointer = 0x164BBB0;
        constexpr uintptr_t SetLabelTextFunctionPointer = 0x1656FF0;
        constexpr uintptr_t UiEnginePointer = 0x24FB910;
        constexpr uintptr_t PlantedC4sPointer = 0x234CF00;
        constexpr uintptr_t GetBombsiteACenter = 0x84FD50;
        constexpr uintptr_t GetBombsiteBCenter = 0x84FDB0;
        constexpr uintptr_t SliderSetValueFunction = 0x9E0BA0;
        constexpr uintptr_t TextEntrySetTextFunction = 0x16793D0;
        constexpr uintptr_t SetItemItemIdFunction = 0xDA4180;
    }
    // Module: engine2.dll
    namespace engine2 {
        constexpr uintptr_t BuildNumber_addr = 0x60CC74;
        constexpr uintptr_t NetworkGameClient_ptr = 0x90A1A0;
        constexpr uintptr_t WindowWidth_addr = 0x90E5C0;
        constexpr uintptr_t WindowHeight_addr = 0x90E5C4;
        constexpr uintptr_t PVSManager_ptr = 0x613440;
    }
    // Module: filesystem_stdio.dll
    namespace filesystem_stdio {
        constexpr uintptr_t FullFileSystem_ptr = 0x2157A0;
    }
    // Module: inputsystem.dll
    namespace inputsystem {
        constexpr uintptr_t InputSystem_ptr = 0x42B50;
        constexpr uintptr_t InputSystemSvc_ptr = 0x42B50;
    }
    // Module: matchmaking.dll
    namespace matchmaking {
        constexpr uintptr_t GameTypes_ptr = 0x1B0F80;
    }
    // Module: networksystem.dll
    namespace networksystem {
        constexpr uintptr_t NetworkSystem_ptr = 0x287EA0;
    }
    // Module: panorama.dll
    namespace panorama {
        constexpr uintptr_t SetPanelStylePropertyFunctionPointer = 0x187B90;
    }
    // Module: particles.dll
    namespace particles {
        constexpr uintptr_t GetParticleManager = 0x579550;
    }
    // Module: rendersystemdx11.dll
    namespace rendersystemdx11 {
        constexpr uintptr_t RenderDeviceMgr_ptr = 0x42B530;
    }
    // Module: scenesystem.dll
    namespace scenesystem {
        constexpr uintptr_t SceneSystem_ptr = 0x8DB490;
        constexpr uintptr_t SceneSystemPointer = 0x8DB490;
    }
    // Module: schemasystem.dll
    namespace schemasystem {
        constexpr uintptr_t SchemaSystem_ptr = 0x76800;
    }
    // Module: soundsystem.dll
    namespace soundsystem {
        constexpr uintptr_t SoundSystem_ptr = 0x512360;
        constexpr uintptr_t SoundChannelsPointer = 0x630040;
    }
    // Module: tier0.dll
    namespace tier0 {
        constexpr uintptr_t CVar_ptr = 0x3A93B0;
    }
}

// a2x/cs2-dumper drop-in layout — every public CS2 cheat
// already includes a header structured exactly like this,
// so this block lets that code consume our output unchanged:
//   using namespace cs2_dumper::offsets::client_dll;
namespace cs2_dumper {
    namespace offsets {
        // Module: client.dll
        namespace client_dll {
            constexpr std::ptrdiff_t dwCSGOInput = 0x2353190;
            constexpr std::ptrdiff_t dwEntityList = 0x24E44E0;
            constexpr std::ptrdiff_t dwGameEntitySystem = 0x24E44E0;
            constexpr std::ptrdiff_t dwGameEntitySystem_highestEntityIndex = 0x2090;
            constexpr std::ptrdiff_t dwGameRules = 0x1A00BB0;
            constexpr std::ptrdiff_t dwGlobalVars = 0x205E6D0;
            constexpr std::ptrdiff_t dwGlowManager = 0x233B050;
            constexpr std::ptrdiff_t dwLocalPlayerController = 0x231D830;
            constexpr std::ptrdiff_t dwLocalPlayerPawn = 0x2069800;
            constexpr std::ptrdiff_t dwPlantedC4 = 0x234CF08;
            constexpr std::ptrdiff_t dwPrediction = 0x2069710;
            constexpr std::ptrdiff_t dwSensitivity = 0x233BB68;
            constexpr std::ptrdiff_t dwSensitivity_sensitivity = 0x58;
            constexpr std::ptrdiff_t dwViewAngles = 0x2353818;
            constexpr std::ptrdiff_t dwViewMatrix = 0x2343AB0;
            constexpr std::ptrdiff_t dwViewRender = 0x2343E58;
            constexpr std::ptrdiff_t dwWeaponC4 = 0x22BBE30;
        }
        // Module: engine2.dll
        namespace engine2_dll {
            constexpr std::ptrdiff_t dwBuildNumber = 0x60CC74;
            constexpr std::ptrdiff_t dwNetworkGameClient = 0x90A1A0;
            constexpr std::ptrdiff_t dwNetworkGameClient_clientTickCount = 0x378;
            constexpr std::ptrdiff_t dwNetworkGameClient_deltaTick = 0x24C;
            constexpr std::ptrdiff_t dwNetworkGameClient_isBackgroundMap = 0x2C141F;
            constexpr std::ptrdiff_t dwNetworkGameClient_localPlayer = 0xF8;
            constexpr std::ptrdiff_t dwNetworkGameClient_maxClients = 0x240;
            constexpr std::ptrdiff_t dwNetworkGameClient_serverTickCount = 0x24C;
            constexpr std::ptrdiff_t dwNetworkGameClient_signOnState = 0x230;
            constexpr std::ptrdiff_t dwWindowHeight = 0x90E5C4;
            constexpr std::ptrdiff_t dwWindowWidth = 0x90E5C0;
        }
        // Module: inputsystem.dll
        namespace inputsystem_dll {
            constexpr std::ptrdiff_t dwInputSystem = 0x42B50;
        }
        // Module: matchmaking.dll
        namespace matchmaking_dll {
            constexpr std::ptrdiff_t dwGameTypes = 0x1B0F80;
        }
        // Module: soundsystem.dll
        namespace soundsystem_dll {
            constexpr std::ptrdiff_t dwSoundSystem = 0x512360;
            constexpr std::ptrdiff_t dwSoundSystem_engineViewData = 0x7C;
        }
    }
}
