// Generated by cs2-sdk — https://cs2-sdk.com
//
// module:        assetbrowser.dll
// classes:       0
// enums:         15
// generated_at:  2026-06-01T19:07:51.721490200+00:00
//
// Use:
//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);
//   pawn->m_iHealth() = 100;

#pragma once
#include "../macros.hpp"

namespace assetbrowser {


    enum class GraphCanvasItemHoverBehavior_t : std::uint32_t {
        HOVER_PROPAGATE = 0x0,
        HOVER_STOP_PROPAGATION = 0x1,
    };

    enum class GraphCanvasInteractionPriority_t : std::int32_t {
        NONINTERACTIVE = -9999,
        GROUP = 0x0,
        BASE = 0x1,
        DRAG_HANDLE = 0x2,
        RESIZE_EDGE = 0x3,
        RESIZE_CORNER = 0x4,
        ADD_FLOW = 0x5,
        PORT = 0x6,
        ANCHOR = 0x7,
    };

    enum class GraphCanvasChildLayoutAlgorithm_t : std::uint32_t {
        DEFAULT = 0x0,
        VBOX = 0x1,
        VBOX_REVERSE = 0x2,
        HBOX = 0x3,
        HBOX_REVERSE = 0x4,
    };

    enum class GraphCanvasBackgroundPosition_t : std::uint32_t {
        Top = 0x0,
        Left = 0x0,
        Center = 0x1,
        Bottom = 0x2,
        Right = 0x2,
    };

    enum class GraphCanvasTextClipMode_t : std::uint32_t {
        EXPAND_ITEM = 0x0,
        CLIP_TEXT = 0x1,
        ELIDE_TEXT_END = 0x2,
        WORD_WRAP = 0x3,
    };

    enum class GraphCanvasBackgroundRepeat_t : std::uint32_t {
        Repeat = 0x0,
        NoRepeat = 0x1,
        RepeatX = 0x2,
        RepeatY = 0x3,
    };

    enum class GraphCanvasBackgroundImageSize_t : std::uint32_t {
        Natural = 0x0,
        Contain = 0x1,
        Cover = 0x2,
        Stretch = 0x3,
    };

    enum class LayoutAxis_t : std::uint32_t {
        X = 0x0,
        Y = 0x1,
    };

    enum class GraphCanvasBorderDrawBehavior_t : std::uint32_t {
        Centered = 0x0,
        Inside = 0x1,
        Outside = 0x2,
    };

    enum class GraphCanvasVAlign_t : std::uint32_t {
        TOP = 0x0,
        CENTER = 0x1,
        BOTTOM = 0x2,
        STRETCH = 0x3,
    };

    enum class GraphCanvasVisibilityState_t : std::uint32_t {
        VISIBLE = 0x0,
        HIDDEN = 0x1,
        COLLAPSE = 0x2,
    };

    enum class GraphCanvasPositioning_t : std::uint32_t {
        AUTO = 0x0,
        INSIDE_PARENT = 0x1,
        OUTSIDE_PARENT = 0x2,
        ON_PARENT_BORDER = 0x3,
    };

    enum class GraphCanvasRenderLayer_t : std::int32_t {
        INVALID = -1,
        COMMENTS = 0x0,
        CONNECTIONS_BACKGROUND = 0x1,
        GROUP_BACKGROUND = 0x2,
        DEFAULT = 0x3,
        NODES = 0x4,
        CONNECTIONS_FOREGROUND = 0x5,
        COMMENT_OVERLAY = 0x6,
        SELECTION_OVERLAY = 0x7,
        HOVER_OVERLAY = 0x8,
        STANDARD_LAYER_COUNT = 0x9,
        SPECIAL_DEBUGGER_OVERLAY = 0xA,
        SPECIAL_LAYER_HOVER_TOOLTIP = 0xB,
    };

    enum class GraphCanvasPseudoClass_t : std::uint32_t {
        INVALID = 0x0,
        FIRST_CHILD = 0x1,
        LAST_CHILD = 0x2,
        NTH_CHILD = 0x3,
        NTH_LAST_CHILD = 0x4,
        ONLY_CHILD = 0x5,
        HOVER_ANCESTOR = 0x6,
        HOVER_DESCENDANT = 0x7,
        HOVER_CUSTOM_A = 0x8,
        HOVER_CUSTOM_B = 0x9,
        HOVER_CUSTOM_C = 0xA,
        SELECTED = 0xB,
        HOVER_SELF = 0xC,
    };

    enum class GraphCanvasHAlign_t : std::uint32_t {
        LEFT = 0x0,
        CENTER = 0x1,
        RIGHT = 0x2,
        STRETCH = 0x3,
    };

} // namespace assetbrowser
