// Generated by cs2-sdk — https://cs2-sdk.com
//
// module:        assetsystem.dll
// classes:       21
// enums:         2
// generated_at:  2026-06-01T19:07:51.721490200+00:00
//
// Use:
//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);
//   pawn->m_iHealth() = 100;

#pragma once
#include "../macros.hpp"

namespace assetsystem {

    class CAssetWarning;
    class CExternalToolInfo;
    class CSimpleAssetTypeInfo;
    class CDetailPropModel;
    class CEngineToolInfo;
    class CMapAssetTypeInfo;
    class CBitmapAssetTypeInfo;
    class CModuleManifests;
    class CDetailPropType;
    class CBaseToolInfo;
    class CAssetTypeConfig;
    class CAssetTagInfo;
    class ResourceBlockTypeInfo_t;
    class CToolsConfig;
    class AssetEngineCommand_t;
    class CSubassetTypeInfo;
    class CResourceAssetTypeInfo;
    class CVMMDAssetTypeInfo;
    class CManifestInfo;
    class AutoTagVDataCondition_t;
    class CAssetWarningCheck;

    enum class ResourceDataEncodingType_t : std::int32_t {
        RESOURCE_ENCODING_INVALID = -1,
        RESOURCE_ENCODING_INTROSPECTED = 0x0,
        RESOURCE_ENCODING_KV3 = 0x1,
        RESOURCE_ENCODING_VTEX = 0x2,
        RESOURCE_ENCODING_RAW_BYTES = 0x3,
        RESOURCE_ENCODING_VSNAP = 0x4,
        RESOURCE_ENCODING_VRMAN = 0x5,
        RESOURCE_ENCODING_COMPILEIMAGEUTILS_TEXT = 0x6,
        RESOURCE_ENCODING_TEXT = 0x7,
        RESOURCE_ENCODING_MBUF = 0x8,
        RESOURCE_ENCODING_MVTX = 0x9,
        RESOURCE_ENCODING_MIDX = 0xA,
        RESOURCE_ENCODING_MSLT = 0xB,
        RESOURCE_ENCODING_LEGACY_VSND = 0xC,
        RESOURCE_ENCODING_COUNT = 0xD,
    };

    enum class AssetWarningFixType_t : std::uint32_t {
        NONE = 0x0,
        VMDL_CONVERT_TO_MODELDOC = 0x1,
        VMAP_MANUAL_RECOMPILE = 0x2,
    };

    // CManifestInfo
    //   fields: 6
    class CManifestInfo {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_Name                                          , 0x0) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_Group                                         , 0x8) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_Mod                                           , 0x10) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_SourceFile                                    , 0x18) // CUtlString
        SCHEMA_FIELD(std::int32_t                    , m_nSourceLine                                   , 0x20) // int32
        SCHEMA_FIELD(CUtlVector<CUtlString>          , m_Resources                                     , 0x28) // CUtlVector<CUtlString>
    };

    // CEngineToolInfo
    //   fields: 11
    class CEngineToolInfo {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_Library                                       , 0x20) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_InterfaceName                                 , 0x28) // CUtlString
        SCHEMA_FIELD(bool                            , m_bShowInRevisionSubMenu                        , 0x30) // bool
        SCHEMA_FIELD(bool                            , m_bIsSecondaryTool                              , 0x31) // bool
        SCHEMA_FIELD(bool                            , m_bDoNotWarnAboutLargeAssetBatches              , 0x32) // bool
        SCHEMA_FIELD(bool                            , m_bIsWorkshopManagerTool                        , 0x33) // bool
        SCHEMA_FIELD(bool                            , m_bIsWorkshopItemTool                           , 0x34) // bool
        SCHEMA_FIELD(bool                            , m_bCanHighlightSubassets                        , 0x35) // bool
        SCHEMA_FIELD(CUtlVector<CUtlString>          , m_AssetTypes                                    , 0x38) // CUtlVector<CUtlString>
        SCHEMA_FIELD(CUtlVector<CUtlString>          , m_LimitToMods                                   , 0x50) // CUtlVector<CUtlString>
        SCHEMA_FIELD(CUtlVector<CUtlString>          , m_ExcludeFromMods                               , 0x68) // CUtlVector<CUtlString>
    };

    // CAssetWarning
    //   fields: 3
    class CAssetWarning {
    public:
        SCHEMA_FIELD(CBufferString                   , m_Title                                         , 0x8) // CBufferString
        SCHEMA_FIELD(CBufferString                   , m_Message                                       , 0x18) // CBufferString
        SCHEMA_FIELD(CUtlVector<CAssetWarningCheck>  , m_Checks                                        , 0x28) // CUtlVector<CAssetWarningCheck>
    };

    // AutoTagVDataCondition_t
    //   fields: 4
    class AutoTagVDataCondition_t {
    public:
        SCHEMA_FIELD(CResourceNameTyped<CWeakHandle<::resourcesystem::InfoForResourceTypeCVDataResource>>, m_SourceFile                                    , 0x0) // CResourceNameTyped<CWeakHandle<InfoForResourceTypeCVDataResource>>
        SCHEMA_FIELD(CKV3MemberNameWithStorage       , m_AssetKey                                      , 0xE0) // CKV3MemberNameWithStorage
        SCHEMA_FIELD(CKV3MemberNameWithStorage       , m_AlternateAssetKey                             , 0x118) // CKV3MemberNameWithStorage
        SCHEMA_FIELD(::CUtlString                    , m_Expression                                    , 0x150) // CUtlString
    };

    // AssetEngineCommand_t
    //   fields: 4
    class AssetEngineCommand_t {
    public:
        SCHEMA_FIELD(CBufferString                   , m_Command                                       , 0x0) // CBufferString
        SCHEMA_FIELD(CBufferString                   , m_Icon                                          , 0x10) // CBufferString
        SCHEMA_FIELD(CBufferString                   , m_Description                                   , 0x20) // CBufferString
        SCHEMA_FIELD(bool                            , m_bBringEngineToFront                           , 0x30) // bool
    };

    // CDetailPropModel
    //   fields: 20
    class CDetailPropModel {
    public:
        SCHEMA_FIELD(CResourceNameTyped<CWeakHandle<InfoForResourceTypeCModel>>, m_ModelName                                     , 0x0) // CResourceNameTyped<CWeakHandle<InfoForResourceTypeCModel>>
        SCHEMA_FIELD(CModelMaterialGroupName         , m_MaterialGroup                                 , 0xE0) // CModelMaterialGroupName
        SCHEMA_FIELD(float                           , m_flWeight                                      , 0xE8) // float32
        SCHEMA_FIELD(float                           , m_flStartFadeSize                               , 0xEC) // float32
        SCHEMA_FIELD(float                           , m_flEndFadeSize                                 , 0xF0) // float32
        SCHEMA_FIELD(float                           , m_flOrientToSurface                             , 0xF4) // float32
        SCHEMA_FIELD(float                           , m_flMinSurfaceSlope                             , 0xF8) // float32
        SCHEMA_FIELD(float                           , m_flMaxSurfaceSlope                             , 0xFC) // float32
        SCHEMA_FIELD(float                           , m_flRandomVerticalOffsetMin                     , 0x100) // float32
        SCHEMA_FIELD(float                           , m_flRandomVerticalOffsetMax                     , 0x104) // float32
        SCHEMA_FIELD(::QAngle                        , m_vRandomRotationMin                            , 0x108) // QAngle
        SCHEMA_FIELD(::QAngle                        , m_vRandomRotationMax                            , 0x114) // QAngle
        SCHEMA_FIELD(float                           , m_flRandomScaleMin                              , 0x120) // float32
        SCHEMA_FIELD(float                           , m_flRandomScaleMax                              , 0x124) // float32
        SCHEMA_FIELD(float                           , m_flDensityMinScale                             , 0x128) // float32
        SCHEMA_FIELD(float                           , m_flBlendWeightMinScale                         , 0x12C) // float32
        SCHEMA_FIELD(float                           , m_flBlendWeightMin                              , 0x130) // float32
        SCHEMA_FIELD(float                           , m_flBlendWeightMax                              , 0x134) // float32
        SCHEMA_FIELD(float                           , m_flBlendWeightFullDenstity                     , 0x138) // float32
        SCHEMA_FIELD(bool                            , m_bCastStaticShadows                            , 0x13C) // bool
    };

    // CDetailPropType
    //   fields: 2
    class CDetailPropType {
    public:
        SCHEMA_FIELD(float                           , m_flDensity                                     , 0x0) // float32
        SCHEMA_FIELD(CUtlVector<CDetailPropModel>    , m_Models                                        , 0x8) // CUtlVector<CDetailPropModel>
    };

    // CVMMDAssetTypeInfo
    //   fields: 0
    class CVMMDAssetTypeInfo {
    public:
    };

    // CToolsConfig
    //   fields: 3
    class CToolsConfig {
    public:
        SCHEMA_FIELD(CUtlVector<CEngineToolInfo>     , m_EngineTools                                   , 0x0) // CUtlVector<CEngineToolInfo>
        SCHEMA_FIELD(CUtlVector<CExternalToolInfo>   , m_ExternalTools                                 , 0x18) // CUtlVector<CExternalToolInfo>
        SCHEMA_FIELD(CUtlVector<CUtlString>          , m_EngineModulesThatReferenceAssets              , 0x30) // CUtlVector<CUtlString>
    };

    // CResourceAssetTypeInfo
    //   fields: 8
    class CResourceAssetTypeInfo {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_CompilerIdentifier                            , 0x100) // CUtlString
        SCHEMA_FIELD(CUtlVector<CUtlString>          , m_CompileDependsOnResourceTypes                 , 0x108) // CUtlVector<CUtlString>
        SCHEMA_FIELD(CUtlVector<ResourceBlockTypeInfo_t>, m_Blocks                                        , 0x120) // CUtlVector<ResourceBlockTypeInfo_t>
        SCHEMA_FIELD(::CUtlString                    , m_RequiredSpecialDependency                     , 0x138) // CUtlString
        SCHEMA_FIELD(bool                            , m_bPreventDirectCompile                         , 0x140) // bool
        SCHEMA_FIELD(bool                            , m_bCannotBeAMultiParentChildCompile             , 0x141) // bool
        SCHEMA_FIELD(bool                            , m_bPrefersIconForThumbnail                      , 0x142) // bool
        SCHEMA_FIELD(bool                            , m_bAllowedToCompileInTestMode                   , 0x143) // bool
    };

    // CBaseToolInfo
    //   fields: 4
    class CBaseToolInfo {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_Name                                          , 0x0) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_OverrideToolShortcutName                      , 0x8) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_FriendlyName                                  , 0x10) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_ToolIcon                                      , 0x18) // CUtlString
    };

    // CAssetWarningCheck
    //   fields: 9
    class CAssetWarningCheck {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_AssetType                                     , 0x0) // CUtlString
        SCHEMA_FIELD(CBufferString                   , m_RequireSearchableIntKey                       , 0x8) // CBufferString
        SCHEMA_FIELD(std::int32_t                    , m_RequireSearchableIntValue                     , 0x18) // int32
        SCHEMA_FIELD(bool                            , m_bOnlyWarnIfGameFilePresent                    , 0x1C) // bool
        SCHEMA_FIELD(bool                            , m_bOnlyWarnIfContentFilePresent                 , 0x1D) // bool
        SCHEMA_FIELD(bool                            , m_bOnlyWarnAddons                               , 0x1E) // bool
        SCHEMA_FIELD(CUtlVector<CUtlString>          , m_ExcludeAddonNames                             , 0x20) // CUtlVector<CUtlString>
        SCHEMA_FIELD(::CUtlString                    , m_FixDescription                                , 0x38) // CUtlString
        SCHEMA_FIELD(AssetWarningFixType_t           , m_FixType                                       , 0x40) // AssetWarningFixType_t
    };

    // CMapAssetTypeInfo
    //   fields: 0
    class CMapAssetTypeInfo {
    public:
    };

    // CSimpleAssetTypeInfo
    //   fields: 24
    class CSimpleAssetTypeInfo {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_FriendlyName                                  , 0x10) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_Ext                                           , 0x18) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_IconLg                                        , 0x20) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_IconSm                                        , 0x28) // CUtlString
        SCHEMA_FIELD(CUtlVector<CUtlString>          , m_SuppressSubstrings                            , 0x30) // CUtlVector<CUtlString>
        SCHEMA_FIELD(CUtlVector<CUtlString>          , m_AdditionalExtensions                          , 0x48) // CUtlVector<CUtlString>
        SCHEMA_FIELD(CUtlVector<AssetEngineCommand_t>, m_EngineCommands                                , 0x60) // CUtlVector<AssetEngineCommand_t>
        SCHEMA_FIELD(CUtlVector<CUtlString>          , m_LimitToMods                                   , 0x78) // CUtlVector<CUtlString>
        SCHEMA_FIELD(CUtlVector<CUtlString>          , m_ExcludeFromMods                               , 0x90) // CUtlVector<CUtlString>
        SCHEMA_FIELD(CUtlVector<CUtlString>          , m_HideForRetailMods                             , 0xA8) // CUtlVector<CUtlString>
        SCHEMA_FIELD(::CUtlString                    , m_PreviewThumbnailOverlayIcon                   , 0xC0) // CUtlString
        SCHEMA_FIELD(bool                            , m_bErrorOnUnrecognizedOutboundRefs              , 0xC8) // bool
        SCHEMA_FIELD(CUtlVector<CUtlString>          , m_UnrecognizedOutboundRefsErrorTypeExceptions   , 0xD0) // CUtlVector<CUtlString>
        SCHEMA_FIELD(bool                            , m_bHideTypeByDefault                            , 0xE8) // bool
        SCHEMA_FIELD(bool                            , m_bCannotBeShown                                , 0xE9) // bool
        SCHEMA_FIELD(bool                            , m_bIsNontrivialChildAssetType                   , 0xEA) // bool
        SCHEMA_FIELD(bool                            , m_bSuppressFullFingerprintCalculation           , 0xEB) // bool
        SCHEMA_FIELD(bool                            , m_bIgnoreCompiledState                          , 0xEC) // bool
        SCHEMA_FIELD(bool                            , m_bContentFileIsText                            , 0xED) // bool
        SCHEMA_FIELD(bool                            , m_bPrefersLivePreview                           , 0xEE) // bool
        SCHEMA_FIELD(bool                            , m_bPresentInGameTree                            , 0xEF) // bool
        SCHEMA_FIELD(bool                            , m_bShouldCompileErrorFallbackToDisk             , 0xF0) // bool
        SCHEMA_FIELD(std::int32_t                    , m_nAssetTypeVersion                             , 0xF4) // int32
        SCHEMA_FIELD(::CUtlString                    , m_Test_InjectSearchable                         , 0xF8) // CUtlString
    };

    // CSubassetTypeInfo
    //   fields: 1
    class CSubassetTypeInfo {
    public:
        SCHEMA_FIELD(bool                            , m_bFollowReferences                             , 0x8) // bool
    };

    // CExternalToolInfo
    //   fields: 8
    class CExternalToolInfo {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_Executable                                    , 0x20) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_Args                                          , 0x28) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_ArgsWithLineColumn                            , 0x30) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_WorkingDir                                    , 0x38) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_MatchSystemExecutable                         , 0x40) // CUtlString
        SCHEMA_FIELD(CUtlVector<CUtlString>          , m_SupportedExts                                 , 0x48) // CUtlVector<CUtlString>
        SCHEMA_FIELD(CUtlVector<CUtlString>          , m_PriorityExts                                  , 0x60) // CUtlVector<CUtlString>
        SCHEMA_FIELD(bool                            , m_bDebugCommandline                             , 0x78) // bool
    };

    // CModuleManifests
    //   fields: 1
    class CModuleManifests {
    public:
        SCHEMA_FIELD(CUtlVector<CManifestInfo>       , m_Manifests                                     , 0x0) // CUtlVector<CManifestInfo>
    };

    // CBitmapAssetTypeInfo
    //   fields: 0
    class CBitmapAssetTypeInfo {
    public:
    };

    // CAssetTypeConfig
    //   fields: 3
    class CAssetTypeConfig {
    public:
        SCHEMA_FIELD(CUtlVector<CSimpleAssetTypeInfo*>, m_AssetTypes                                    , 0x0) // CUtlVector<CSimpleAssetTypeInfo*>
        SCHEMA_FIELD(CUtlVector<CSubassetTypeInfo*>  , m_SubassetTypes                                 , 0x18) // CUtlVector<CSubassetTypeInfo*>
        SCHEMA_FIELD(CUtlVector<CAssetWarning*>      , m_AssetWarnings                                 , 0x30) // CUtlVector<CAssetWarning*>
    };

    // ResourceBlockTypeInfo_t
    //   fields: 4
    class ResourceBlockTypeInfo_t {
    public:
        SCHEMA_FIELD(ResourceDataEncodingType_t      , m_Encoding                                      , 0x0) // ResourceDataEncodingType_t
        SCHEMA_FIELD(::CUtlString                    , m_BlockID                                       , 0x8) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_IntrospectedRootStruct                        , 0x10) // CUtlString
        SCHEMA_FIELD(std::int32_t                    , m_ResourceVersion                               , 0x18) // int32
    };

    // CAssetTagInfo
    //   fields: 11
    class CAssetTagInfo {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_TagName                                       , 0x30) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_TagDescription                                , 0x38) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_TagIcon                                       , 0x40) // CUtlString
        SCHEMA_FIELD(::Color                         , m_TagColor                                      , 0x48) // Color
        SCHEMA_FIELD(CUtlVector<CUtlString>          , m_TagAliases                                    , 0x50) // CUtlVector<CUtlString>
        SCHEMA_FIELD(::CUtlString                    , m_ThumbnailOverlayImage                         , 0x68) // CUtlString
        SCHEMA_FIELD(bool                            , m_bTagIndicatesRejectedAsset                    , 0x70) // bool
        SCHEMA_FIELD(bool                            , m_bTagHidesAssetByDefault                       , 0x71) // bool
        SCHEMA_FIELD(::CUtlString                    , m_RestrictAutoTagToAssetType                    , 0x78) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_AutoFilterTag                                 , 0x80) // CUtlString
        SCHEMA_FIELD(AutoTagVDataCondition_t         , m_AutoDataTag                                   , 0x88) // AutoTagVDataCondition_t
    };

} // namespace assetsystem
