// Generated by cs2-sdk — https://cs2-sdk.com
//
// module:        assetpreview.dll
// classes:       35
// enums:         1
// generated_at:  2026-06-01T19:07:51.721490200+00:00
//
// Use:
//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);
//   pawn->m_iHealth() = 100;

#pragma once
#include "../macros.hpp"

namespace assetpreview {

    class CSmartPropPulse_FitOnLine;
    class CSmartPropPulse_SelectionEndCap_Criteria_t;
    class CSmartPropOperationAPI;
    class CSmartPropPulse_SelectionLinearLength_Criteria_t;
    class CSmartPropPulse_SelectionChoiceWeight;
    class CSmartPropPulse_SelectionEndCap;
    class CSmartPropOperation_MaterialReplacementAPI;
    class CSmartPropPulse_PlaceOnPath;
    class CSmartPropAPI;
    class CSmartPropPulse_Group;
    class CSmartPropPulse_SmartProp;
    class CSmartPropPulse_CreateRotator;
    class CSmartPropPulse_CriteriaPathPosition;
    class CSmartPropPulse_BaseQueryableFlow;
    class CSmartPropExprAPI;
    class CSmartPropPulse_PlaceInSphere;
    class CSmartPropFilterAPI;
    class CSmartPropPulse_CriteriaPathPosition_Criteria_t;
    class CSmartPropPulse_CreateLocator;
    class CSmartPropPulse_SelectionChoiceWeight_Criteria_t;
    class CSmartPropPulse_CreateSizer;
    class CSmartPropPulse_PickOneSelector;
    class CPulseGraphInstance_SmartPropEval;
    class CSmartPropPulse_SelectionLinearLength;
    class CLightRigBackground;
    class CLightRigExposure;
    class CLightRigSky;
    class CLightRigSpotLight;
    class CLightRigSunLight;
    class CLightRigPostProcessing;
    class CLightRigGrid;
    class CLightRigPointLight;
    class CLightRigLight;
    class CLightRigVMap;
    class CToolSceneLightRig;

    enum class LightRigType_t : std::uint32_t {
        PREVIEW = 0x0,
        THUMBNAIL = 0x1,
        MATERIAL_THUMBNAIL = 0x2,
        NUM_TYPES = 0x3,
    };

    // CPulseGraphInstance_SmartPropEval
    //   fields: 0
    class CPulseGraphInstance_SmartPropEval {
    public:
    };

    // CSmartPropPulse_BaseQueryableFlow
    //   fields: 0
    class CSmartPropPulse_BaseQueryableFlow {
    public:
    };

    // CSmartPropFilterAPI
    //   fields: 0
    class CSmartPropFilterAPI {
    public:
    };

    // CSmartPropPulse_CreateSizer
    //   fields: 7
    class CSmartPropPulse_CreateSizer {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_Name                                          , 0x48) // CUtlString
        SCHEMA_FIELD(bool                            , m_bHACK_ProvideResultMinX                       , 0x50) // bool
        SCHEMA_FIELD(bool                            , m_bHACK_ProvideResultMaxX                       , 0x51) // bool
        SCHEMA_FIELD(bool                            , m_bHACK_ProvideResultMinY                       , 0x52) // bool
        SCHEMA_FIELD(bool                            , m_bHACK_ProvideResultMaxY                       , 0x53) // bool
        SCHEMA_FIELD(bool                            , m_bHACK_ProvideResultMinZ                       , 0x54) // bool
        SCHEMA_FIELD(bool                            , m_bHACK_ProvideResultMaxZ                       , 0x55) // bool
    };

    // CSmartPropOperation_MaterialReplacementAPI
    //   fields: 0
    class CSmartPropOperation_MaterialReplacementAPI {
    public:
    };

    // CLightRigLight
    //   fields: 11
    class CLightRigLight {
    public:
        SCHEMA_FIELD(::Vector                        , m_vPosition                                     , 0x0) // Vector
        SCHEMA_FIELD(::Vector                        , m_vDirection                                    , 0xC) // Vector
        SCHEMA_FIELD(::Vector                        , m_vLookAt                                       , 0x18) // Vector
        SCHEMA_FIELD(::Color                         , m_Color                                         , 0x24) // Color
        SCHEMA_FIELD(float                           , m_flAxisScale                                   , 0x28) // float32
        SCHEMA_FIELD(float                           , m_flRadius                                      , 0x2C) // float32
        SCHEMA_FIELD(float                           , m_flBrightness                                  , 0x30) // float32
        SCHEMA_FIELD(float                           , m_flLightSourceRadius                           , 0x34) // float32
        SCHEMA_FIELD(float                           , m_flDistance                                    , 0x38) // float32
        SCHEMA_FIELD(bool                            , m_bRelativePositioning                          , 0x3C) // bool
        SCHEMA_FIELD(bool                            , m_bParentToCamera                               , 0x3D) // bool
    };

    // CSmartPropPulse_CreateRotator
    //   fields: 1
    class CSmartPropPulse_CreateRotator {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_Name                                          , 0x48) // CUtlString
    };

    // CLightRigGrid
    //   fields: 2
    class CLightRigGrid {
    public:
        SCHEMA_FIELD(bool                            , m_bEnabled                                      , 0x0) // bool
        SCHEMA_FIELD(::Color                         , m_Color                                         , 0x1) // Color
    };

    // CLightRigSpotLight
    //   fields: 3
    class CLightRigSpotLight {
    public:
        SCHEMA_FIELD(float                           , m_flOuterConeAngle                              , 0x40) // float32
        SCHEMA_FIELD(float                           , m_flInnerConeAngle                              , 0x44) // float32
        SCHEMA_FIELD(bool                            , m_bCastShadows                                  , 0x48) // bool
    };

    // CLightRigVMap
    //   fields: 3
    class CLightRigVMap {
    public:
        SCHEMA_FIELD(CResourceNameTyped<CWeakHandle<::worldrenderer::InfoForResourceTypeVMapResourceData_t>>, m_MapName                                       , 0x0) // CResourceNameTyped<CWeakHandle<InfoForResourceTypeVMapResourceData_t>>
        SCHEMA_FIELD(bool                            , m_bRender3DSkybox                               , 0xE0) // bool
        SCHEMA_FIELD(bool                            , m_bParticlesTraceAgainstMap                     , 0xE1) // bool
    };

    // CSmartPropPulse_PlaceInSphere
    //   fields: 1
    class CSmartPropPulse_PlaceInSphere {
    public:
        SCHEMA_FIELD(::animationsystem::CPulse_OutflowConnection, m_Place                                         , 0x48) // CPulse_OutflowConnection
    };

    // CSmartPropPulse_SelectionChoiceWeight::Criteria_t
    //   fields: 1
    class CSmartPropPulse_SelectionChoiceWeight_Criteria_t {
    public:
        SCHEMA_FIELD(float                           , m_flWeight                                      , 0x0) // float32
    };

    // CSmartPropPulse_SelectionLinearLength::Criteria_t
    //   fields: 4
    class CSmartPropPulse_SelectionLinearLength_Criteria_t {
    public:
        SCHEMA_FIELD(float                           , m_flLength                                      , 0x0) // float32
        SCHEMA_FIELD(bool                            , m_bAllowScale                                   , 0x4) // bool
        SCHEMA_FIELD(float                           , m_flMinLength                                   , 0x8) // float32
        SCHEMA_FIELD(float                           , m_flMaxLength                                   , 0xC) // float32
    };

    // CSmartPropPulse_CreateLocator
    //   fields: 1
    class CSmartPropPulse_CreateLocator {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_LocatorName                                   , 0x48) // CUtlString
    };

    // CLightRigSunLight
    //   fields: 5
    class CLightRigSunLight {
    public:
        SCHEMA_FIELD(float                           , m_flShadowCascadeDistance0                      , 0x40) // float32
        SCHEMA_FIELD(float                           , m_flShadowCascadeDistance1                      , 0x44) // float32
        SCHEMA_FIELD(float                           , m_flShadowCascadeDistance2                      , 0x48) // float32
        SCHEMA_FIELD(float                           , m_flShadowCascadeDistance3                      , 0x4C) // float32
        SCHEMA_FIELD(bool                            , m_bCastShadows                                  , 0x50) // bool
    };

    // CLightRigBackground
    //   fields: 2
    class CLightRigBackground {
    public:
        SCHEMA_FIELD(bool                            , m_bEnabled                                      , 0x0) // bool
        SCHEMA_FIELD(::Color                         , m_Color                                         , 0x1) // Color
    };

    // CSmartPropPulse_SelectionEndCap::Criteria_t
    //   fields: 2
    class CSmartPropPulse_SelectionEndCap_Criteria_t {
    public:
        SCHEMA_FIELD(bool                            , m_bStart                                        , 0x0) // bool
        SCHEMA_FIELD(bool                            , m_bEnd                                          , 0x1) // bool
    };

    // CLightRigSky
    //   fields: 1
    class CLightRigSky {
    public:
        SCHEMA_FIELD(CStrongHandle<InfoForResourceTypeIMaterial2>, m_hSkyMaterial                                  , 0x0) // CStrongHandle<InfoForResourceTypeIMaterial2>
    };

    // CLightRigPointLight
    //   fields: 0
    class CLightRigPointLight {
    public:
    };

    // CSmartPropExprAPI
    //   fields: 0
    class CSmartPropExprAPI {
    public:
    };

    // CSmartPropAPI
    //   fields: 0
    class CSmartPropAPI {
    public:
    };

    // CSmartPropOperationAPI
    //   fields: 0
    class CSmartPropOperationAPI {
    public:
    };

    // CSmartPropPulse_CriteriaPathPosition::Criteria_t
    //   fields: 5
    class CSmartPropPulse_CriteriaPathPosition_Criteria_t {
    public:
        SCHEMA_FIELD(::assetrename::SmartPropPathPositions_t, m_PlaceAtPositions                              , 0x0) // SmartPropPathPositions_t
        SCHEMA_FIELD(std::int32_t                    , m_nPlaceEveryNthPosition                        , 0x4) // int32
        SCHEMA_FIELD(std::int32_t                    , m_nNthPositionIndexOffset                       , 0x8) // int32
        SCHEMA_FIELD(bool                            , m_bAllowAtStart                                 , 0xC) // bool
        SCHEMA_FIELD(bool                            , m_bAllowAtEnd                                   , 0xD) // bool
    };

    // CLightRigExposure
    //   fields: 3
    class CLightRigExposure {
    public:
        SCHEMA_FIELD(bool                            , m_bEnabled                                      , 0x0) // bool
        SCHEMA_FIELD(float                           , m_flMinEV                                       , 0x4) // float32
        SCHEMA_FIELD(float                           , m_flMaxEV                                       , 0x8) // float32
    };

    // CSmartPropPulse_PlaceOnPath
    //   fields: 2
    class CSmartPropPulse_PlaceOnPath {
    public:
        SCHEMA_FIELD(::animationsystem::PulseSelectorOutflowList_t, m_OutflowList                                   , 0x48) // PulseSelectorOutflowList_t
        SCHEMA_FIELD(::CUtlString                    , m_PathName                                      , 0x60) // CUtlString
    };

    // CLightRigPostProcessing
    //   fields: 1
    class CLightRigPostProcessing {
    public:
        SCHEMA_FIELD(CStrongHandle<InfoForResourceTypeCPostProcessingResource>, m_hPostProcessing                               , 0x0) // CStrongHandle<InfoForResourceTypeCPostProcessingResource>
    };

    // CToolSceneLightRig
    //   fields: 10
    class CToolSceneLightRig {
    public:
        SCHEMA_FIELD(LightRigType_t                  , m_nRigType                                      , 0x8) // LightRigType_t
        SCHEMA_FIELD(CUtlVector<CLightRigSunLight>   , m_Suns                                          , 0x10) // CUtlVector<CLightRigSunLight>
        SCHEMA_FIELD(CUtlVector<CLightRigPointLight> , m_PointLights                                   , 0x28) // CUtlVector<CLightRigPointLight>
        SCHEMA_FIELD(CUtlVector<CLightRigSpotLight>  , m_SpotLights                                    , 0x40) // CUtlVector<CLightRigSpotLight>
        SCHEMA_FIELD(CLightRigBackground             , m_Background                                    , 0x58) // CLightRigBackground
        SCHEMA_FIELD(CLightRigGrid                   , m_Grid                                          , 0x5D) // CLightRigGrid
        SCHEMA_FIELD(CLightRigExposure               , m_Exposure                                      , 0x64) // CLightRigExposure
        SCHEMA_FIELD(CLightRigPostProcessing         , m_PostProcessing                                , 0x70) // CLightRigPostProcessing
        SCHEMA_FIELD(CLightRigSky                    , m_Sky                                           , 0x78) // CLightRigSky
        SCHEMA_FIELD(CLightRigVMap                   , m_BackgroundMap                                 , 0x80) // CLightRigVMap
    };

    // CSmartPropPulse_FitOnLine
    //   fields: 1
    class CSmartPropPulse_FitOnLine {
    public:
        SCHEMA_FIELD(::animationsystem::PulseSelectorOutflowList_t, m_OutflowList                                   , 0x48) // PulseSelectorOutflowList_t
    };

    // CSmartPropPulse_SelectionChoiceWeight
    //   fields: 0
    class CSmartPropPulse_SelectionChoiceWeight {
    public:
    };

    // CSmartPropPulse_SmartProp
    //   fields: 1
    class CSmartPropPulse_SmartProp {
    public:
        SCHEMA_FIELD(CStrongHandle<::resourcesystem::InfoForResourceTypeCSmartProp>, m_hSmartProp                                    , 0x48) // CStrongHandle<InfoForResourceTypeCSmartProp>
    };

    // CSmartPropPulse_Group
    //   fields: 1
    class CSmartPropPulse_Group {
    public:
        SCHEMA_FIELD(::animationsystem::PulseSelectorOutflowList_t, m_OutflowList                                   , 0x48) // PulseSelectorOutflowList_t
    };

    // CSmartPropPulse_SelectionEndCap
    //   fields: 0
    class CSmartPropPulse_SelectionEndCap {
    public:
    };

    // CSmartPropPulse_SelectionLinearLength
    //   fields: 0
    class CSmartPropPulse_SelectionLinearLength {
    public:
    };

    // CSmartPropPulse_CriteriaPathPosition
    //   fields: 0
    class CSmartPropPulse_CriteriaPathPosition {
    public:
    };

    // CSmartPropPulse_PickOneSelector
    //   fields: 2
    class CSmartPropPulse_PickOneSelector {
    public:
        SCHEMA_FIELD(::assetrename::ConfigurationHandleShape_t, m_HandleShape                                   , 0x48) // ConfigurationHandleShape_t
        SCHEMA_FIELD(::animationsystem::PulseSelectorOutflowList_t, m_OutflowList                                   , 0x50) // PulseSelectorOutflowList_t
    };

} // namespace assetpreview
