// Generated by cs2-sdk — https://cs2-sdk.com
//
// module:        met.dll
// classes:       3
// enums:         0
// generated_at:  2026-06-01T19:07:51.721490200+00:00
//
// Use:
//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);
//   pawn->m_iHealth() = 100;

#pragma once
#include "../macros.hpp"

namespace met {

    class EMaterialLayer_t;
    class EMaterialVariables_t;
    class EMaterialVariable_t;

    // EMaterialVariables_t
    //   fields: 3
    class EMaterialVariables_t {
    public:
        SCHEMA_FIELD(bool                            , m_bIsLayeredShader                              , 0x0) // bool
        SCHEMA_FIELD(CUtlVector<EMaterialVariable_t> , m_Variables                                     , 0x8) // CUtlVector<EMaterialVariable_t>
        SCHEMA_FIELD(CUtlVector<EMaterialLayer_t>    , m_Layers                                        , 0x20) // CUtlVector<EMaterialLayer_t>
    };

    // EMaterialLayer_t
    //   fields: 8
    class EMaterialLayer_t {
    public:
        using _Type0 = CUtlVector<std::pair<CUtlString,CUtlString>>;
        SCHEMA_FIELD(CUtlVector<CUtlString>          , m_VariableNames                                 , 0x0) // CUtlVector<CUtlString>
        SCHEMA_FIELD(_Type0                          , m_HiddenVariableUiNames                         , 0x18) // CUtlVector<std::pair<CUtlString,CUtlString>>
        SCHEMA_FIELD(std::int32_t                    , m_ReferenceVariableIndex                        , 0x30) // int32
        SCHEMA_FIELD(::CUtlString                    , m_RefType                                       , 0x38) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_RefFileEnding                                 , 0x40) // CUtlString
        SCHEMA_FIELD(bool                            , m_bActive                                       , 0x48) // bool
        SCHEMA_FIELD(KeyValues3                      , inheritedVariableValues                         , 0x50) // KeyValues3
        SCHEMA_FIELD(KeyValues3                      , inheritedVariableSources                        , 0x60) // KeyValues3
    };

    // EMaterialVariable_t
    //   fields: 36
    class EMaterialVariable_t {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_Name                                          , 0x0) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_ExportName                                    , 0x8) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_UiName                                        , 0x10) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_UiOptions                                     , 0x18) // CUtlString
        SCHEMA_FIELD(bool                            , m_bEnabled                                      , 0x20) // bool
        SCHEMA_FIELD(bool                            , m_bHidden                                       , 0x21) // bool
        SCHEMA_FIELD(::CUtlString                    , m_EnumLabel                                     , 0x28) // CUtlString
        SCHEMA_FIELD(std::int32_t                    , m_nLayerId                                      , 0x30) // int32
        SCHEMA_FIELD(bool                            , m_bLayerAllowOverride                           , 0x34) // bool
        SCHEMA_FIELD(bool                            , m_bLayerReference                               , 0x35) // bool
        SCHEMA_FIELD(::CUtlString                    , m_inheritedValue                                , 0x38) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_inheritedValueSource                          , 0x40) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_Group                                         , 0x48) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_SubGroup                                      , 0x50) // CUtlString
        SCHEMA_FIELD(std::int32_t                    , m_nSortKeyGroup                                 , 0x58) // int32
        SCHEMA_FIELD(std::int32_t                    , m_nSortKeySubGroup                              , 0x5C) // int32
        SCHEMA_FIELD(std::int32_t                    , m_nSortKeyVariable                              , 0x60) // int32
        SCHEMA_FIELD(::CUtlString                    , m_error                                         , 0x68) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_expression                                    , 0x70) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_referencedExpressionPath                      , 0x78) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_referencedValuePath                           , 0x80) // CUtlString
        SCHEMA_FIELD(std::int32_t                    , m_nElements                                     , 0x88) // int32
        SCHEMA_FIELD(::CUtlString                    , m_value                                         , 0x90) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_default                                       , 0x98) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_min                                           , 0xA0) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_max                                           , 0xA8) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_step                                          , 0xB0) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_precision                                     , 0xB8) // CUtlString
        SCHEMA_FIELD(bool                            , m_bInitialTextureInput                          , 0xC0) // bool
        SCHEMA_FIELD(std::int32_t                    , m_nTextureAutoFillCount                         , 0xC4) // int32
        SCHEMA_FIELD(::CUtlString                    , m_alternateInput                                , 0xC8) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_defaultColor                                  , 0xD0) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_defaultInput                                  , 0xD8) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_textureSuffix                                 , 0xE0) // CUtlString
        SCHEMA_FIELD(::CUtlString                    , m_defaultSlider                                 , 0xE8) // CUtlString
        SCHEMA_FIELD(float                           , m_fDefaultSlider                                , 0xF0) // float32[2]
    };

} // namespace met
