// Generated by cs2-sdk — https://cs2-sdk.com
//
// module:        modtools.dll
// classes:       2
// enums:         0
// generated_at:  2026-06-01T19:07:51.721490200+00:00
//
// Use:
//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);
//   pawn->m_iHealth() = 100;

#pragma once
#include "../macros.hpp"

namespace modtools {

    class CNmGraphDocAimCSNode;
    class CnmGraphDocSnapWeaponNode;

    // CnmGraphDocSnapWeaponNode
    //   fields: 0
    class CnmGraphDocSnapWeaponNode {
    public:
    };

    // CNmGraphDocAimCSNode
    //   fields: 3
    class CNmGraphDocAimCSNode {
    public:
        SCHEMA_FIELD(float                           , m_flActionBlendTimeSeconds                      , 0x100) // float32
        SCHEMA_FIELD(float                           , m_flHandIKBlendInTimeSeconds                    , 0x104) // float32
        SCHEMA_FIELD(float                           , m_flPlantingBlendTimeSeconds                    , 0x108) // float32
    };

} // namespace modtools
